image: node:lts-alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  only:
    - master
  script:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.78.2/hugo_0.78.2_Linux-64bit.tar.gz
    - tar zxvf hugo_0.78.2_Linux-64bit.tar.gz
    - cd themes/design-system-gouvfr && npm install && cd ../../
    - cp -r themes/design-system-gouvfr/node_modules/@gouvfr/dsfr/dist/ ./static/design-system-gouvfr
    - ./hugo -b https://peren.gitlab.io/website/website/
  artifacts:
    paths:
      - public
  cache:
    paths:
      - themes/design-system-gouvfr/node_modules
