name: Deploy Pages

on:
  push:
    branches:
      - pages  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: dokku/github-action@master
        with:
          ci_branch_name: pages
          git_remote_url: 'ssh://dokku@app.etalab.studio:22/10pourcent'
          ssh_private_key: ${{ secrets.DOKKU_DEPLOYMENT_SSH_PRIVATE_KEY }}
          # git_push_flags: "--force"
